[phases.setup]
nixPkgs = ["python3", "gcc"]

[phases.install]
cmds = [
  "echo 'Skipping default pip install; Poetry handled in build script'"
]

[phases.build]
cmds = [
  "bash ./scripts/railway_build.sh"
]

[start]
cmd = "bash ./scripts/railway_start.sh"
